const mongoose = require('mongoose');
const Cocktail = require('../models/Cocktail');
require('dotenv').config();

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/nauti-bouys', {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const additionalCocktails = [
  {
    name: "Classic Martini",
    description: "The quintessential gin cocktail, crisp and clean with a perfect balance of gin and dry vermouth",
    ingredients: [
      { name: "Premium Gin", amount: "2.5", unit: "oz" },
      { name: "Dry Vermouth", amount: "0.5", unit: "oz" },
      { name: "Lemon Twist", amount: "1", unit: "piece" }
    ],
    prepMethod: "Stir gin and vermouth with ice in mixing glass. Strain into chilled martini glass. Garnish with lemon twist.",
    price: 15,
    category: "Gin",
    glassType: "Martini",
    garnish: "Lemon twist or olive",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 28,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Herbal", "Crisp", "Clean"],
    tags: ["Classic", "Gin", "Elegant"],
    allergens: []
  },
  {
    name: "Manhattan",
    description: "A timeless whiskey cocktail with sweet vermouth and aromatic bitters, served up or on the rocks",
    ingredients: [
      { name: "Rye Whiskey", amount: "2", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Angostura Bitters", amount: "2", unit: "dash" },
      { name: "Maraschino Cherry", amount: "1", unit: "piece" }
    ],
    prepMethod: "Stir all ingredients with ice. Strain into chilled coupe glass. Garnish with cherry.",
    price: 16,
    category: "Whiskey",
    glassType: "Coupe",
    garnish: "Maraschino cherry",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 30,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Whiskey", "Sweet", "Herbal", "Smooth"],
    tags: ["Classic", "Whiskey", "Sophisticated"],
    allergens: []
  },
  {
    name: "Negroni",
    description: "Equal parts gin, Campari, and sweet vermouth create this perfectly balanced bitter Italian classic",
    ingredients: [
      { name: "Gin", amount: "1", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Orange Peel", amount: "1", unit: "piece" }
    ],
    prepMethod: "Stir all ingredients with ice. Strain over large ice cube in rocks glass. Express orange peel oils and garnish.",
    price: 14,
    category: "Gin",
    glassType: "Rocks",
    garnish: "Orange peel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 24,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "Clear",
    tastingNotes: ["Bitter", "Herbal", "Orange", "Complex"],
    tags: ["Classic", "Italian", "Bitter"],
    allergens: []
  },
  {
    name: "Whiskey Sour",
    description: "A perfect balance of whiskey, fresh lemon juice, and simple syrup, topped with a silky foam",
    ingredients: [
      { name: "Bourbon Whiskey", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Egg White", amount: "1", unit: "piece" }
    ],
    prepMethod: "Dry shake all ingredients. Add ice and shake again. Double strain into coupe glass.",
    price: 13,
    category: "Whiskey",
    glassType: "Coupe",
    garnish: "Lemon wheel and cherry",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 22,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Whiskey", "Citrus", "Sweet", "Smooth"],
    tags: ["Classic", "Sour", "Foam"],
    allergens: ["Egg"]
  },
  {
    name: "Daiquiri",
    description: "The perfect rum cocktail showcasing the spirit with lime juice and simple syrup in perfect harmony",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled coupe glass.",
    price: 12,
    category: "Rum",
    glassType: "Coupe",
    garnish: "Lime wheel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 20,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Rum",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Rum", "Lime", "Sweet", "Refreshing"],
    tags: ["Classic", "Rum", "Citrus"],
    allergens: []
  },
  {
    name: "Margarita",
    description: "Mexico's gift to the world - tequila, lime, and orange liqueur in perfect balance",
    ingredients: [
      { name: "Blanco Tequila", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Cointreau", amount: "0.75", unit: "oz" },
      { name: "Salt", amount: "1", unit: "piece" }
    ],
    prepMethod: "Rim glass with salt. Shake all ingredients with ice. Strain over fresh ice in rocks glass.",
    price: 13,
    category: "Tequila",
    glassType: "Rocks",
    garnish: "Lime wheel and salt rim",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 22,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Tequila",
    servingTemp: "Chilled",
    ice: "Cube",
    tastingNotes: ["Tequila", "Lime", "Orange", "Salty"],
    tags: ["Classic", "Mexican", "Citrus"],
    allergens: []
  },
  {
    name: "Cosmopolitan",
    description: "The sophisticated pink cocktail that defined the 90s, with vodka, cranberry, and lime",
    ingredients: [
      { name: "Vodka", amount: "1.5", unit: "oz" },
      { name: "Cointreau", amount: "0.5", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Cranberry Juice", amount: "0.5", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled martini glass.",
    price: 14,
    category: "Vodka",
    glassType: "Martini",
    garnish: "Lime wheel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 18,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Vodka",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Vodka", "Cranberry", "Lime", "Tart"],
    tags: ["Modern Classic", "Pink", "Sophisticated"],
    allergens: []
  },
  {
    name: "Mojito",
    description: "Cuba's refreshing mint and lime cocktail with white rum, perfect for hot summer days",
    ingredients: [
      { name: "White Rum", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Fresh Mint", amount: "8", unit: "piece" },
      { name: "Club Soda", amount: "2", unit: "oz" }
    ],
    prepMethod: "Muddle mint gently in glass. Add rum, lime juice, and syrup. Fill with ice and top with soda.",
    price: 13,
    category: "Rum",
    glassType: "Highball",
    garnish: "Fresh mint sprig and lime wheel",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 15,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Rum",
    servingTemp: "Chilled",
    ice: "Cube",
    tastingNotes: ["Rum", "Mint", "Lime", "Refreshing"],
    tags: ["Cuban", "Mint", "Refreshing"],
    allergens: []
  },
  {
    name: "Espresso Martini",
    description: "The perfect pick-me-up cocktail combining vodka with fresh espresso and coffee liqueur",
    ingredients: [
      { name: "Vodka", amount: "2", unit: "oz" },
      { name: "Fresh Espresso", amount: "1", unit: "oz" },
      { name: "Kahlúa", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.25", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients vigorously with ice. Double strain into chilled martini glass.",
    price: 15,
    category: "Vodka",
    glassType: "Martini",
    garnish: "Three coffee beans",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 20,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Vodka",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Coffee", "Vodka", "Sweet", "Rich"],
    tags: ["Modern", "Coffee", "After Dinner"],
    allergens: []
  },
  {
    name: "Aperol Spritz",
    description: "Italy's beloved aperitivo - light, bubbly, and perfectly bitter-sweet with Aperol and Prosecco",
    ingredients: [
      { name: "Aperol", amount: "3", unit: "oz" },
      { name: "Prosecco", amount: "3", unit: "oz" },
      { name: "Club Soda", amount: "1", unit: "oz" },
      { name: "Orange Slice", amount: "1", unit: "piece" }
    ],
    prepMethod: "Build in wine glass over ice. Add Aperol, then Prosecco, top with soda. Stir gently.",
    price: 12,
    category: "Modern",
    glassType: "Wine",
    garnish: "Orange slice",
    difficulty: "Easy",
    preparationTime: 1,
    alcoholContent: 11,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Liqueur",
    servingTemp: "Chilled",
    ice: "Cube",
    tastingNotes: ["Bitter", "Orange", "Bubbly", "Light"],
    tags: ["Italian", "Aperitif", "Low ABV"],
    allergens: []
  },
  {
    name: "French 75",
    description: "Elegant champagne cocktail with gin, lemon juice, and simple syrup - effervescent sophistication",
    ingredients: [
      { name: "Gin", amount: "1", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Champagne", amount: "3", unit: "oz" }
    ],
    prepMethod: "Shake gin, lemon juice, and syrup with ice. Strain into flute and top with champagne.",
    price: 16,
    category: "Classic",
    glassType: "Specialty",
    garnish: "Lemon twist",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 15,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Lemon", "Bubbly", "Elegant"],
    tags: ["French", "Champagne", "Celebration"],
    allergens: []
  },
  {
    name: "Pisco Sour",
    description: "Peru's national cocktail featuring pisco brandy, lime juice, and a silky egg white foam",
    ingredients: [
      { name: "Pisco", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Simple Syrup", amount: "0.75", unit: "oz" },
      { name: "Egg White", amount: "1", unit: "piece" },
      { name: "Angostura Bitters", amount: "3", unit: "dash" }
    ],
    prepMethod: "Dry shake all ingredients except bitters. Add ice and shake again. Strain into coupe. Dot with bitters.",
    price: 14,
    category: "Classic",
    glassType: "Coupe",
    garnish: "Angostura bitters dots",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 20,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Brandy",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Pisco", "Lime", "Smooth", "Tart"],
    tags: ["Peruvian", "Sour", "Foam"],
    allergens: ["Egg"]
  },
  {
    name: "Aviation",
    description: "A sophisticated gin cocktail with maraschino liqueur and crème de violette for floral complexity",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Maraschino Liqueur", amount: "0.5", unit: "oz" },
      { name: "Crème de Violette", amount: "0.25", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.5", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled coupe glass.",
    price: 15,
    category: "Gin",
    glassType: "Coupe",
    garnish: "Lemon twist",
    difficulty: "Medium",
    preparationTime: 2,
    alcoholContent: 25,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Floral", "Cherry", "Complex"],
    tags: ["Classic", "Floral", "Complex"],
    allergens: []
  },
  {
    name: "Paper Plane",
    description: "Modern classic equal-parts cocktail with bourbon, Aperol, Amaro, and lemon juice",
    ingredients: [
      { name: "Bourbon Whiskey", amount: "0.75", unit: "oz" },
      { name: "Aperol", amount: "0.75", unit: "oz" },
      { name: "Amaro Nonino", amount: "0.75", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled coupe glass.",
    price: 16,
    category: "Whiskey",
    glassType: "Coupe",
    garnish: "None",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 22,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Whiskey", "Bitter", "Herbal", "Balanced"],
    tags: ["Modern Classic", "Equal Parts", "Bitter"],
    allergens: []
  },
  {
    name: "Bee's Knees",
    description: "Prohibition-era gin cocktail sweetened with honey syrup and brightened with fresh lemon",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Honey Syrup", amount: "0.75", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled coupe glass.",
    price: 13,
    category: "Gin",
    glassType: "Coupe",
    garnish: "Lemon twist",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 22,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Honey", "Lemon", "Smooth"],
    tags: ["Prohibition", "Honey", "Classic"],
    allergens: []
  },
  {
    name: "Last Word",
    description: "Equal parts gin, green Chartreuse, maraschino liqueur, and lime juice create this herbal masterpiece",
    ingredients: [
      { name: "Gin", amount: "0.75", unit: "oz" },
      { name: "Green Chartreuse", amount: "0.75", unit: "oz" },
      { name: "Maraschino Liqueur", amount: "0.75", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.75", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into chilled coupe glass.",
    price: 17,
    category: "Gin",
    glassType: "Coupe",
    garnish: "None",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 25,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Herbal", "Complex", "Lime", "Unique"],
    tags: ["Equal Parts", "Herbal", "Complex"],
    allergens: []
  },
  {
    name: "Corpse Reviver #2",
    description: "The most famous of the corpse reviver series - gin, Cointreau, Lillet, lemon, and absinthe",
    ingredients: [
      { name: "Gin", amount: "0.75", unit: "oz" },
      { name: "Cointreau", amount: "0.75", unit: "oz" },
      { name: "Lillet Blanc", amount: "0.75", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Absinthe", amount: "1", unit: "dash" }
    ],
    prepMethod: "Rinse coupe with absinthe. Shake remaining ingredients with ice. Double strain into glass.",
    price: 16,
    category: "Gin",
    glassType: "Coupe",
    garnish: "Orange twist",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 24,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Orange", "Herbal", "Complex"],
    tags: ["Classic", "Equal Parts", "Absinthe"],
    allergens: []
  },
  {
    name: "Ramos Gin Fizz",
    description: "New Orleans classic requiring 12 minutes of shaking for the perfect creamy, foamy texture",
    ingredients: [
      { name: "Gin", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.5", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "0.5", unit: "oz" },
      { name: "Simple Syrup", amount: "0.5", unit: "oz" },
      { name: "Egg White", amount: "1", unit: "piece" },
      { name: "Heavy Cream", amount: "1", unit: "oz" },
      { name: "Club Soda", amount: "2", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients except soda for 12 minutes. Strain into collins glass and slowly top with soda.",
    price: 18,
    category: "Gin",
    glassType: "Highball",
    garnish: "None",
    difficulty: "Hard",
    preparationTime: 15,
    alcoholContent: 15,
    specialty: true,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Gin",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Gin", "Creamy", "Citrus", "Luxurious"],
    tags: ["New Orleans", "Fizz", "Labor Intensive"],
    allergens: ["Egg", "Dairy"]
  },
  {
    name: "Sazerac",
    description: "New Orleans' official cocktail - rye whiskey, sugar, Peychaud's bitters, and an absinthe rinse",
    ingredients: [
      { name: "Rye Whiskey", amount: "2", unit: "oz" },
      { name: "Sugar Cube", amount: "1", unit: "piece" },
      { name: "Peychaud's Bitters", amount: "3", unit: "dash" },
      { name: "Absinthe", amount: "1", unit: "dash" }
    ],
    prepMethod: "Rinse rocks glass with absinthe. Muddle sugar and bitters. Add whiskey and ice. Stir and strain into glass.",
    price: 17,
    category: "Whiskey",
    glassType: "Rocks",
    garnish: "Lemon peel (expressed, not dropped)",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 35,
    specialty: true,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "None",
    tastingNotes: ["Whiskey", "Anise", "Spice", "Historic"],
    tags: ["New Orleans", "Historic", "Absinthe"],
    allergens: []
  },
  {
    name: "Vieux Carré",
    description: "New Orleans cocktail combining rye whiskey, cognac, sweet vermouth, and two types of bitters",
    ingredients: [
      { name: "Rye Whiskey", amount: "1", unit: "oz" },
      { name: "Cognac", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" },
      { name: "Bénédictine", amount: "0.25", unit: "oz" },
      { name: "Peychaud's Bitters", amount: "2", unit: "dash" },
      { name: "Angostura Bitters", amount: "2", unit: "dash" }
    ],
    prepMethod: "Stir all ingredients with ice. Strain over large ice cube in rocks glass.",
    price: 18,
    category: "Whiskey",
    glassType: "Rocks",
    garnish: "Lemon twist",
    difficulty: "Medium",
    preparationTime: 2,
    alcoholContent: 32,
    specialty: true,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "Clear",
    tastingNotes: ["Whiskey", "Cognac", "Herbal", "Complex"],
    tags: ["New Orleans", "Complex", "Stirred"],
    allergens: []
  },
  {
    name: "Boulevardier",
    description: "The whiskey version of a Negroni - bourbon, Campari, and sweet vermouth in perfect harmony",
    ingredients: [
      { name: "Bourbon Whiskey", amount: "1.5", unit: "oz" },
      { name: "Campari", amount: "1", unit: "oz" },
      { name: "Sweet Vermouth", amount: "1", unit: "oz" }
    ],
    prepMethod: "Stir all ingredients with ice. Strain over large ice cube in rocks glass.",
    price: 15,
    category: "Whiskey",
    glassType: "Rocks",
    garnish: "Orange peel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 28,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "Clear",
    tastingNotes: ["Whiskey", "Bitter", "Sweet", "Balanced"],
    tags: ["Negroni Variation", "Bitter", "Stirred"],
    allergens: []
  },
  {
    name: "Gold Rush",
    description: "Modern classic whiskey sour variation using honey syrup instead of simple syrup",
    ingredients: [
      { name: "Bourbon Whiskey", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Honey Syrup", amount: "0.75", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Double strain into rocks glass over large ice cube.",
    price: 14,
    category: "Whiskey",
    glassType: "Rocks",
    garnish: "Lemon wheel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 25,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "Clear",
    tastingNotes: ["Whiskey", "Honey", "Lemon", "Smooth"],
    tags: ["Modern Classic", "Honey", "Sour"],
    allergens: []
  },
  {
    name: "Penicillin",
    description: "Modern classic Scotch cocktail with honey, lemon, ginger, and a smoky Islay Scotch float",
    ingredients: [
      { name: "Blended Scotch", amount: "2", unit: "oz" },
      { name: "Fresh Lemon Juice", amount: "0.75", unit: "oz" },
      { name: "Honey-Ginger Syrup", amount: "0.75", unit: "oz" },
      { name: "Islay Scotch", amount: "0.25", unit: "oz" }
    ],
    prepMethod: "Shake first three ingredients with ice. Strain over fresh ice. Float Islay Scotch on top.",
    price: 16,
    category: "Whiskey",
    glassType: "Rocks",
    garnish: "Candied ginger",
    difficulty: "Medium",
    preparationTime: 3,
    alcoholContent: 25,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Whiskey",
    servingTemp: "Chilled",
    ice: "Cube",
    tastingNotes: ["Scotch", "Ginger", "Honey", "Smoky"],
    tags: ["Modern Classic", "Smoky", "Ginger"],
    allergens: []
  },
  {
    name: "Tommy's Margarita",
    description: "Simplified margarita using agave nectar instead of orange liqueur for pure agave flavor",
    ingredients: [
      { name: "Blanco Tequila", amount: "2", unit: "oz" },
      { name: "Fresh Lime Juice", amount: "1", unit: "oz" },
      { name: "Agave Nectar", amount: "0.5", unit: "oz" }
    ],
    prepMethod: "Shake all ingredients with ice. Strain over fresh ice in rocks glass.",
    price: 13,
    category: "Tequila",
    glassType: "Rocks",
    garnish: "Lime wheel",
    difficulty: "Easy",
    preparationTime: 2,
    alcoholContent: 24,
    specialty: false,
    isAvailable: true,
    isSignature: false,
    primarySpirit: "Tequila",
    servingTemp: "Chilled",
    ice: "Cube",
    tastingNotes: ["Tequila", "Lime", "Agave", "Clean"],
    tags: ["Modern Classic", "Agave", "Simple"],
    allergens: []
  }
];

async function seedCocktails() {
  try {
    console.log('🍸 Starting to seed additional cocktails...');
    
    // Insert additional cocktails
    const cocktailResults = await Cocktail.insertMany(additionalCocktails);
    console.log(`🍸 Added ${cocktailResults.length} additional cocktails`);
    
    console.log('✅ Successfully seeded additional cocktails!');
    console.log(`📋 Total new cocktails: ${cocktailResults.length}`);
    
  } catch (error) {
    console.error('❌ Error seeding cocktails:', error);
  } finally {
    mongoose.connection.close();
    console.log('🔌 Database connection closed');
  }
}

// Run the seed function
seedCocktails();
