const spirits = [
  // Premium Whiskeys & Bourbons
  {
    name: "Pappy Van Winkle 23 Year",
    brand: "Pappy Van Winkle",
    description: "The holy grail of bourbon. Aged 23 years, this wheated bourbon offers unparalleled complexity with notes of vanilla, caramel, and oak.",
    type: "Whiskey",
    subType: "Bourbon",
    distillery: "Buffalo Trace",
    origin: "Kentucky, USA",
    age: 23,
    abv: 47.8,
    price: 8000,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "pappy-van-winkle-23-bourbon.jpg",
    isAvailable: true,
    tastingNotes: ["vanilla", "caramel", "oak", "honey", "spice"],
    averageRating: 4.9
  },
  {
    name: "Macallan 25 Year Sherry Oak",
    brand: "Macallan",
    description: "Exceptional single malt Scotch whisky matured exclusively in hand-picked sherry seasoned oak casks from Jerez.",
    type: "Whiskey",
    subType: "Scotch",
    distillery: "Macallan",
    origin: "Scotland",
    age: 25,
    abv: 43,
    price: 2500,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "macallan-25-sherry-oak-scotch.jpg",
    isAvailable: true,
    tastingNotes: ["sherry", "dried fruits", "chocolate", "spice", "oak"],
    averageRating: 4.8
  },
  {
    name: "Blanton's Single Barrel",
    brand: "Blanton's",
    description: "The original single barrel bourbon. Each bottle comes from a single barrel, making every bottle unique.",
    type: "Whiskey",
    subType: "Bourbon",
    distillery: "Buffalo Trace",
    origin: "Kentucky, USA",
    age: 8,
    abv: 46.5,
    price: 200,
    bottleSize: "750ml",
    isPremium: true,
    image: "blantons-single-barrel-bourbon.jpg",
    isAvailable: true,
    tastingNotes: ["citrus", "vanilla", "honey", "spice", "leather"],
    averageRating: 4.6
  },
  {
    name: "Weller 12 Year",
    brand: "W.L. Weller",
    description: "Wheated bourbon with exceptional smoothness. Part of the same mash bill family as Pappy Van Winkle.",
    type: "Whiskey",
    subType: "Bourbon",
    distillery: "Buffalo Trace",
    origin: "Kentucky, USA",
    age: 12,
    abv: 45,
    price: 400,
    bottleSize: "750ml",
    isPremium: true,
    image: "weller-12-year-bourbon.jpg",
    isAvailable: true,
    tastingNotes: ["wheat", "vanilla", "caramel", "fruit", "smooth"],
    averageRating: 4.5
  },
  {
    name: "Yamazaki 18 Year",
    brand: "Yamazaki",
    description: "Japan's most celebrated single malt whisky. Aged in a variety of cask types including American oak and sherry.",
    type: "Whiskey",
    subType: "Japanese Single Malt",
    distillery: "Suntory",
    origin: "Japan",
    age: 18,
    abv: 43,
    price: 3500,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "yamazaki-18-japanese-whisky.jpg",
    isAvailable: true,
    tastingNotes: ["mizunara oak", "incense", "honey", "orange", "spice"],
    averageRating: 4.9
  },

  // Premium Tequilas & Mezcals
  {
    name: "Clase Azul Reposado",
    brand: "Clase Azul",
    description: "Ultra-premium tequila aged in American whiskey barrels. Each bottle is hand-painted by Mexican artisans.",
    type: "Tequila",
    subType: "Reposado",
    distillery: "Clase Azul",
    origin: "Mexico",
    age: 0.67,
    abv: 40,
    price: 150,
    bottleSize: "750ml",
    isPremium: true,
    image: "clase-azul-reposado-tequila.jpg",
    isAvailable: true,
    tastingNotes: ["agave", "vanilla", "caramel", "wood", "smooth"],
    averageRating: 4.7
  },
  {
    name: "Don Julio 1942",
    brand: "Don Julio",
    description: "Premium añejo tequila celebrating the year Don Julio González began his tequila-making journey.",
    type: "Tequila",
    subType: "Añejo",
    distillery: "Don Julio",
    origin: "Mexico",
    age: 2.5,
    abv: 40,
    price: 180,
    bottleSize: "750ml",
    isPremium: true,
    image: "don-julio-1942-tequila.jpg",
    isAvailable: true,
    tastingNotes: ["agave", "chocolate", "vanilla", "tropical fruit", "oak"],
    averageRating: 4.6
  },
  {
    name: "Del Maguey Vida Mezcal",
    brand: "Del Maguey",
    description: "Single village mezcal from San Luis del Rio. Smoky, complex, and traditionally produced.",
    type: "Mezcal",
    subType: "Joven",
    distillery: "Del Maguey",
    origin: "Mexico",
    abv: 42,
    price: 45,
    bottleSize: "750ml",
    image: "del-maguey-vida-mezcal.jpg",
    isAvailable: true,
    tastingNotes: ["smoke", "earth", "agave", "pepper", "mineral"],
    averageRating: 4.4
  },
  {
    name: "Fortaleza Blanco",
    brand: "Fortaleza",
    description: "Traditional tequila made using tahona wheel and copper pot stills. Pure expression of agave.",
    type: "Tequila",
    subType: "Blanco",
    distillery: "Fortaleza",
    origin: "Mexico",
    abv: 40,
    price: 55,
    bottleSize: "750ml",
    isPremium: true,
    image: "fortaleza-blanco-tequila.jpg",
    isAvailable: true,
    tastingNotes: ["agave", "citrus", "pepper", "mineral", "clean"],
    averageRating: 4.5
  },

  // Premium Gins
  {
    name: "Hendrick's Gin",
    brand: "Hendrick's",
    description: "Distinctively crafted gin infused with cucumber and rose petals. Served best with cucumber.",
    type: "Gin",
    subType: "London Dry",
    distillery: "Hendrick's",
    origin: "Scotland",
    abv: 44,
    price: 35,
    bottleSize: "750ml",
    image: "hendricks-gin.jpg",
    isAvailable: true,
    tastingNotes: ["cucumber", "rose", "juniper", "citrus", "floral"],
    averageRating: 4.3
  },
  {
    name: "Monkey 47 Gin",
    brand: "Monkey 47",
    description: "German gin with 47 botanicals including lingonberries. Complex and sophisticated.",
    type: "Gin",
    subType: "Schwarzwald Dry",
    distillery: "Monkey 47",
    origin: "Germany",
    abv: 47,
    price: 45,
    bottleSize: "500ml",
    isPremium: true,
    image: "monkey-47-gin.jpg",
    isAvailable: true,
    tastingNotes: ["juniper", "lingonberry", "herbs", "spice", "complex"],
    averageRating: 4.6
  },
  {
    name: "The Botanist Gin",
    brand: "The Botanist",
    description: "Islay dry gin featuring 22 hand-foraged local botanicals from the Scottish island of Islay.",
    type: "Gin",
    subType: "Islay Dry",
    distillery: "Bruichladdich",
    origin: "Scotland",
    abv: 46,
    price: 40,
    bottleSize: "750ml",
    image: "botanist-gin.jpg",
    isAvailable: true,
    tastingNotes: ["juniper", "herbs", "floral", "citrus", "maritime"],
    averageRating: 4.4
  },

  // Premium Rums
  {
    name: "Appleton Estate 21 Year",
    brand: "Appleton Estate",
    description: "Jamaican rum aged for a minimum of 21 years. Rich, complex, and full of tropical character.",
    type: "Rum",
    subType: "Aged",
    distillery: "Appleton Estate",
    origin: "Jamaica",
    age: 21,
    abv: 43,
    price: 350,
    bottleSize: "750ml",
    isPremium: true,
    image: "appleton-estate-21-rum.jpg",
    isAvailable: true,
    tastingNotes: ["tropical fruit", "vanilla", "spice", "oak", "molasses"],
    averageRating: 4.7
  },
  {
    name: "Diplomatico Reserva Exclusiva",
    brand: "Diplomatico",
    description: "Venezuelan rum aged up to 12 years. Sweet, smooth, and incredibly complex.",
    type: "Rum",
    subType: "Aged",
    distillery: "Diplomatico",
    origin: "Venezuela",
    age: 12,
    abv: 40,
    price: 45,
    bottleSize: "750ml",
    image: "diplomatico-reserva-exclusiva-rum.jpg",
    isAvailable: true,
    tastingNotes: ["caramel", "chocolate", "fruit", "vanilla", "smooth"],
    averageRating: 4.5
  },
  {
    name: "Mount Gay XO",
    brand: "Mount Gay",
    description: "Barbadian rum aged 8-15 years. The world's oldest rum brand with exceptional craftsmanship.",
    type: "Rum",
    subType: "Extra Old",
    distillery: "Mount Gay",
    origin: "Barbados",
    age: 12,
    abv: 43,
    price: 65,
    bottleSize: "750ml",
    image: "mount-gay-xo-rum.jpg",
    isAvailable: true,
    tastingNotes: ["banana", "vanilla", "spice", "oak", "tropical"],
    averageRating: 4.4
  },

  // Premium Vodkas
  {
    name: "Grey Goose",
    brand: "Grey Goose",
    description: "French vodka made from winter wheat and spring water from Gensac-la-Pallue.",
    type: "Vodka",
    subType: "Premium",
    distillery: "Grey Goose",
    origin: "France",
    abv: 40,
    price: 45,
    bottleSize: "750ml",
    image: "grey-goose-vodka.jpg",
    isAvailable: true,
    tastingNotes: ["clean", "smooth", "wheat", "neutral", "crisp"],
    averageRating: 4.2
  },
  {
    name: "Beluga Gold Line",
    brand: "Beluga",
    description: "Russian vodka rested for 90 days after filtration. Comes with a leather case.",
    type: "Vodka",
    subType: "Ultra Premium",
    distillery: "Beluga",
    origin: "Russia",
    abv: 40,
    price: 85,
    bottleSize: "750ml",
    isPremium: true,
    image: "beluga-gold-line-vodka.jpg",
    isAvailable: true,
    tastingNotes: ["smooth", "clean", "grain", "soft", "premium"],
    averageRating: 4.5
  },

  // More Rare Whiskeys
  {
    name: "Buffalo Trace Antique Collection",
    brand: "Buffalo Trace",
    description: "Annual limited release collection featuring some of the finest aged whiskeys.",
    type: "Whiskey",
    subType: "Bourbon",
    distillery: "Buffalo Trace",
    origin: "Kentucky, USA",
    age: 15,
    abv: 57.4,
    price: 800,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "buffalo-trace-antique-collection-bourbon.jpg",
    isAvailable: true,
    tastingNotes: ["oak", "vanilla", "spice", "fruit", "powerful"],
    averageRating: 4.8
  },
  {
    name: "Lagavulin 16 Year",
    brand: "Lagavulin",
    description: "Islay single malt Scotch whisky with intense peat smoke and maritime character.",
    type: "Whiskey",
    subType: "Scotch",
    distillery: "Lagavulin",
    origin: "Scotland",
    age: 16,
    abv: 43,
    price: 90,
    bottleSize: "750ml",
    isPremium: true,
    image: "lagavulin-16-scotch.jpg",
    isAvailable: true,
    tastingNotes: ["peat", "smoke", "sea salt", "vanilla", "intense"],
    averageRating: 4.6
  },
  {
    name: "Redbreast 21 Year",
    brand: "Redbreast",
    description: "Irish single pot still whiskey aged in bourbon and sherry casks. Exceptional complexity.",
    type: "Whiskey",
    subType: "Irish Single Pot Still",
    distillery: "Irish Distillers",
    origin: "Ireland",
    age: 21,
    abv: 46,
    price: 450,
    bottleSize: "750ml",
    isPremium: true,
    image: "redbreast-21-irish-whiskey.jpg",
    isAvailable: true,
    tastingNotes: ["fruit", "spice", "sherry", "oak", "complex"],
    averageRating: 4.7
  },
  {
    name: "Michter's 20 Year Bourbon",
    brand: "Michter's",
    description: "Ultra-premium American whiskey aged for two decades. Limited annual release.",
    type: "Whiskey",
    subType: "Bourbon",
    distillery: "Michter's",
    origin: "Kentucky, USA",
    age: 20,
    abv: 57.1,
    price: 4500,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "michters-20-year-bourbon.jpg",
    isAvailable: true,
    tastingNotes: ["oak", "vanilla", "caramel", "spice", "luxurious"],
    averageRating: 4.9
  },

  // Additional Premium Spirits
  {
    name: "Hennessy Paradis",
    brand: "Hennessy",
    description: "Exceptional cognac blending eaux-de-vie aged up to 130 years. The pinnacle of cognac craftsmanship.",
    type: "Brandy",
    subType: "Cognac",
    distillery: "Hennessy",
    origin: "France",
    age: 25,
    abv: 40,
    price: 450,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "hennessy-paradis-cognac.jpg",
    isAvailable: true,
    tastingNotes: ["grape", "oak", "vanilla", "fruit", "elegant"],
    averageRating: 4.8
  },
  {
    name: "Johnnie Walker Blue Label",
    brand: "Johnnie Walker",
    description: "Premium blended Scotch whisky. Each bottle is one of a kind, drawn from rare casks.",
    type: "Whiskey",
    subType: "Blended Scotch",
    distillery: "Johnnie Walker",
    origin: "Scotland",
    abv: 40,
    price: 200,
    bottleSize: "750ml",
    isPremium: true,
    image: "johnnie-walker-blue-label-scotch.jpg",
    isAvailable: true,
    tastingNotes: ["honey", "vanilla", "smoke", "fruit", "smooth"],
    averageRating: 4.4
  },
  {
    name: "Patron En Lalique Serie 2",
    brand: "Patron",
    description: "Ultra-premium tequila presented in a handcrafted Lalique crystal decanter.",
    type: "Tequila",
    subType: "Extra Añejo",
    distillery: "Patron",
    origin: "Mexico",
    age: 8,
    abv: 40,
    price: 7500,
    bottleSize: "750ml",
    isPremium: true,
    isTopShelf: true,
    image: "patron-en-lalique-serie-2-tequila.jpg",
    isAvailable: true,
    tastingNotes: ["agave", "oak", "vanilla", "fruit", "luxurious"],
    averageRating: 4.8
  }
]

module.exports = spirits
